name: CI
on:
  workflow_dispatch:
  push:
jobs:
  run-pyp2spec:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - name: install deps
      run: dnf -y install rpm-build rpmdevtools copr-cli
    - run: |
        python -m pip install pyp2spec
        pyp2spec pello
        spectool -gR python-pello.spec
        rpmbuild -bs python-pello.spec
        copr build ksurma/ghtest --nowait ~/rpmbuild/SRPMS/*.src.rpm

  # selftest:
  #   permissions:
  #     contents: read
  #     packages: read
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/copr-build:latest
  #   steps:
  #     - name: checkout to execute local action
  #       uses: actions/checkout@v3
  #     - name: trigger copr build
  #       uses: akdev1l/copr-build@main
  #       id: selftest
  #       env:
  #         COPR_API_TOKEN_CONFIG: ${{ secrets.COPR_API_TOKEN_CONFIG }}
  #       with:
  #         owner: ksurma
  #         package-name: pello
  #         project-name: personal
  #         git-remote: https://github.com/akdev1l/ublue-update.git